version: "3"

services:
  redis:
    image: redis
    sysctls:
      net.core.somaxconn: 1024
    command: ["redis-server", "--appendonly", "yes"]
  php:
    build: .
    volumes:
      - ./:/var/www/html
